hyperion-mc/hyperion

Cargo.lock, Dockerfile, chunk/src/chunk.rs, server/Cargo.toml, server/src/blocks.rs, server/src/main.rs, server/src/system/player_join_world.rs
=> feat: include terrain

generator-build/src/lib.rs, generator/build.rs
- no longer unzips the generated.zip file to the OUT_DIR when a single file can easily be read from the zip file
- this prevents multiple unzips in the `target` directory when the build is run multiple times
=> feat: improve space when rebuilding

Cargo.lock, crates/server/Cargo.toml, crates/server/src/lib.rs, crates/server/src/net.rs
Before this, packets that were received could take 2 ticks to be processed because they need to be moved from LOCAL_PACKETS to GLOBAL_PACKETS. To fix this, LOCAL_PACKETS is removed and a spin lock is used for GLOBAL_PACKETS.
This fixes #94 because the increased ping is a symptom of packets taking up to 2 ticks to be handled. With this fix, ping over localhost should just be the wait_duration for each tick (usually 50ms, but varies slightly)
=> perf: use spin mutex for GLOBAL_PACKETS

.gitignore, Cargo.lock, crates/server/Cargo.toml, crates/server/src/config.rs, crates/server/src/global.rs, crates/server/src/lib.rs, crates/server/src/net.rs, crates/server/src/system/player_join_world.rs, run/config.toml
Add global configuration that reads from `run/config.toml`.
Closes #97
=> Add support for configuration files

Cargo.toml, crates/server/src/config.rs, crates/server/src/net.rs, crates/server/src/system/egress_local.rs, crates/server/src/system/player_join_world.rs
https://doc.rust-lang.org/beta/alloc/vec/struct.Vec.html#guarantees
> `Vec` will never automatically shrink itself, even if completely empty
When chunks are sent, there is a significant allocation in the first gametick. This commit implements re-allocating after the first gametick.
With 1000 players before:
after:
=> perf: improve memory usage (now ~50MB / 1000 players)

crates/server/src/lib.rs, crates/server/src/net.rs
I haven't tested this in an environment that blocks io_uring, but in theory, this should work better than the original check.
=> feat: check if monoio is using io uring (#84)

crates/server/src/system/clean_up_io.rs, crates/server/src/system/player_join_world.rs, crates/server/src/system/update_time.rs
Don't send player remove packets unless needed. Only sync time every 5 seconds.
=> perf: reduce unnecessary packets

crates/server/src/events.rs, crates/server/src/lib.rs, crates/server/src/net/encoder.rs, crates/server/src/net/linux.rs, crates/server/src/system/ingress.rs
packe encoding was bugged and often resulted in disconnects for a couple of reasons:
1. compression threshold used `>=` instead of `>` which caused packets to be compressed when they shouldn't have been
2. the scratch buffer was not *always* cleared before use, causing old data to be appended to the new packet
=> fix: packet encoding

crates/server/src/system/player_join_world.rs
follow up to #351 
`chunk` is `Err` when there is a parsing error or something.
When the chunk is just not loaded `chunk` is `Ok(None)`,
=> feat: show warning when failed to load chunk

crates/server/src/event.rs, crates/server/src/lib.rs
SIGNIFICANTLY reduces mspt on macOS when idling (by factor of 10 probably)
=> perf: remove unnecessary allocations

Cargo.lock, Cargo.toml, crates/server/Cargo.toml, crates/server/src/blocks.rs, crates/server/src/components/chunks.rs, crates/server/src/components/chunks/loader.rs, crates/server/src/components/chunks/region.rs, deny.toml
on server join 32x32 render distance is about twice as fast (about 1.1s to 529ms) and uses significantly fewer cores. This is because most the wait was due to blocking I/O operations.
=> perf: load chunks with tokio

Cargo.lock, crates/server/Cargo.toml, crates/server/src/event.rs, crates/server/src/lib.rs, crates/server/src/system/stats_message.rs
This commit adds a boss bar to the server that shows the current server stats.
This includes:
- ms/tick
- player count
- ms/tick is colored red if it is over 10ms/tick and measures proportion of ms/tick out of 20ms/tick.
- player count is colored white and measures proportion of players out of 10k.
=> feat: add stats boss bar

crates/server/src/event.rs, crates/server/src/inventory.rs, crates/server/src/packets.rs, crates/server/src/system/inventory_systems.rs, crates/server/src/system/release_item.rs, crates/server/src/system/update_equipment.rs
This uses correct arrow speeds and removes arrows from the inventory when they're shot. This also includes some minor refactoring to the inventory API that I thought would've been useful for implementing this but ended up not using, but I left the changes in here since it'll likely be useful later.
Many of the calculations for arrow speed are based off of [Cuberite](https://github.com/cuberite/cuberite/blob/a66a67c2ab50aee3f17015eb48df92e11d9597a1/src/Items/ItemBow.h#L47), modified to be more efficient.
=> feat: arrow speeds and depletion

crates/hyperion/src/common/util/mojang.rs, crates/hyperion/src/ingress/mod.rs, crates/hyperion/src/lib.rs
Addresses high memory usage in the Mojang API client by:
- Reuse single reqwest::Client instance instead of creating new ones
- Implement rate limiting via Semaphore to prevent request flooding
- Add configurable API providers (Mojang/matdoes.dev) with different rate limits
- Auto-reset rate limits using tokio intervals
Breaking changes:
- Remove `MojangClient::default()` in favor of explicit initialization
The previous implementation would create many HTTP clients and flood the API with 
requests, leading to excessive memory usage. This fix ensures proper request 
pacing and connection reuse.
=> fix: Add rate limiting & reuse HTTP client to reduce memory usage

crates/hyperion/src/simulation/util.rs
reverts the rename so everything works fine again
=> fix: automatic map download

crates/hyperion-inventory/src/lib.rs
=> fix: try_add_item

Cargo.lock, Cargo.toml, crates/hyperion-utils/Cargo.toml, crates/hyperion-utils/src/cached_save.rs, crates/hyperion-utils/src/lib.rs, crates/hyperion/Cargo.toml, crates/hyperion/src/common/runtime.rs, crates/hyperion/src/egress/player_join/mod.rs, crates/hyperion/src/egress/sync_entity_state.rs, crates/hyperion/src/lib.rs, crates/hyperion/src/simulation/blocks/manager.rs, crates/hyperion/src/simulation/blocks/mod.rs, crates/hyperion/src/simulation/blocks/shared.rs, crates/hyperion/src/simulation/handlers.rs, crates/hyperion/src/simulation/mod.rs, crates/hyperion/src/simulation/util.rs, events/proof-of-concept/src/lib.rs
- Add `hyperion-utils` module with cached save functionality for world data
- Refactor async runtime to handle scheduled tasks with world context
- Move world loading logic out of simulation module into utilities
- Add `AppId` component for system-level operations and caching
- Update dependencies including `divan` and add streaming features to `reqwest`
- Make block loading more flexible by accepting custom save paths
=> feat: implement configurable world saves & improve async runtime

Cargo.lock, Cargo.toml, crates/hyperion-inventory/src/lib.rs, crates/hyperion-palette/src/lib.rs, crates/hyperion-rank-tree/src/inventory.rs, crates/hyperion-rank-tree/src/lib.rs, crates/hyperion/src/simulation/blocks/chunk.rs, crates/hyperion/src/simulation/blocks/loader/parse/section.rs, crates/hyperion/src/simulation/blocks/mod.rs, events/proof-of-concept/Cargo.toml, events/proof-of-concept/src/command.rs, events/proof-of-concept/src/command/rank.rs, events/proof-of-concept/src/command/replace.rs
- Add command to convert orange concrete (placeholder) into mineable ore deposits
- Implement weighted random ore selection (40% cobble, 35% copper, 15% iron, etc)
- Group connected blocks to create natural-looking ore veins
- Preserve ore type within each group/vein for realistic deposits
- Use parallel block scanning for efficient world traversal
=> feat: `/replace` command for placeholder blocks → mineable ores

crates/hyperion-clap/src/lib.rs, events/tag/src/command/fly.rs
Update the fly command to toggle flying state instead of only enabling it.
Add proper component initialization for the Flight component:
- Track flight state in Flight component
- Register Flight component with meta for UI visibility
- Automatically add Flight component to new Players
- Update packet flags based on current flight state
- Fixes #607
=> fix(commands): `/fly` properly toggles

Cargo.lock, Cargo.toml, crates/hyperion-command/Cargo.toml, crates/hyperion-command/src/system.rs
RegEx is really slow. If used in something like chat commands where they are potentially spammed all the time it can lead to bad performance.
=> perf: remove regex

crates/hyperion-gui/src/lib.rs, events/tag/src/command/gui.rs
ClickMode for flexibility on how the player clicked an item on the GUI
Also there is a bug where the player is able to shift click and take the items. Not sure how to prevent this.
=> feat: add `ClickMode` to GUI API

crates/hyperion-proxy/src/lib.rs, crates/hyperion-proxy/src/player.rs, crates/hyperion/src/lib.rs, events/tag/src/lib.rs
The `gen` is a reserved keyword in 2024 edition; let's use `gen_blocks` instead.
=> feat: use `gen_blocks` instead of `coroutines`

crates/hyperion/src/simulation/metadata/living_entity.rs, events/tag/src/module/attack.rs
Changes:
- Send HealthUpdateS2c to update health on the client
- Send DamageTiltS2c to trigger the damage tilt on the client (still needs to calculate where the damage comes from)
- Send EntityDamageS2c to display a red outline hover the client taking damage
- Send knockback sound to nearby clients
- Send DeathMessageS2c to trigger the client's respawn sequence
- Broadcast EntityStatusS2c when a player is killed
- Set killed player pose to `Dying`
Missing:
- Handle respawn
- Handle critical hits
=> feat(core): send more combat related packets

Dockerfile
=> ci: add cargo doc

crates/hyperion/src/alloc.rs
Allocating zeroed memory is faster than zeroing memory manually. More information is here: https://vorpus.org/blog/why-does-calloc-exist/
=> perf: use alloc zeroed to implement calloc

crates/hyperion/src/lib.rs, crates/hyperion/src/net/encoder/mod.rs
Previously, the code took a reference to uninitialized memory, which is undefined behavior. Allocating zeroed memory is relatively cheap, so the scratch buffer allocates zeroed memory to initialize the memory.
=> fix: initialize scratch buffer

.github/workflows/publish.yml
arm64 seems to take too long and GitHub Actions eventually times out.
=> ci(publish): only build amd64 for now

crates/hyperion/src/simulation/event.rs, crates/hyperion/src/simulation/handlers.rs, crates/hyperion/src/storage/event/queue/mod.rs
PluginMessage was never consumed anywhere and caused an abort because of this.
=> fix: remove PluginMessage

crates/hyperion/src/simulation/blocks/mod.rs
Without this, the code would panic. This can be triggered by shooting an arrow directly up.
=> fix(blocks): return void air above height limit

crates/bvh-region/src/query/closest.rs, crates/bvh-region/tests/simple.rs
Previously, the code would panic when calling get_closest on an empty bvh. One way to trigger this is to use the /spawn command and then leave the game. This fix makes it return None with an empty bvh.
=> fix(bvh-region): get_closest on empty bvh

events/tag/src/module/attack.rs, events/tag/src/module/spawn.rs
This fixes a panic that would've occured from fastrand due to having an empty range due to there being no teammates.
=> fix: respawning without teammates

Cargo.lock, crates/hyperion-respawn/src/lib.rs, crates/hyperion/src/egress/player_join/mod.rs, crates/hyperion/src/egress/sync_entity_state.rs, crates/hyperion/src/simulation/blocks/mod.rs, crates/hyperion/src/simulation/event.rs, crates/hyperion/src/simulation/handlers.rs, crates/hyperion/src/simulation/mod.rs, crates/hyperion/src/storage/event/queue/mod.rs, events/tag/src/command/fly.rs, events/tag/src/command/speed.rs, events/tag/src/lib.rs, events/tag/src/module.rs, events/tag/src/module/attack.rs, events/tag/src/module/damage.rs
This PR aims to standardize player position handling notably teleportations and velocity changes.
Right now every module does its own thing and sends packets directly to the client so it is impossible for the server to keep track of the player's state.
By normalizing the way to change player position/velocity it could allow us to implement better movement verification and better on_ground calculation in the future.
=> fix: better player movement handling

Cargo.lock, crates/hyperion/src/ingress/mod.rs
```
fatal: flecs.c: 17269: assert: arr[last].entity == e INTERNAL_ERROR
```
Reproduce:
```
cargo run -p hyperion-proxy
cargo run -p tag
just bots 
```
=> feat: update latest flecs

GOVERNANCE.md
This PR defines a process under which the governance document can be changed. Given the current lack of this process, this PR is considered a Major change under current governance, and as such requires 2 Core contributor approvals.
=> chore(governance): define process for changing governance

crates/hyperion/src/simulation/handlers.rs
Without saturating_add, the server may panic if it receives too many movement packets within one tick.
=> fix: use saturating_add on received_movement_packets

crates/hyperion/src/ingress/mod.rs
The server can skip fetching the skin in this case because the player does not have a skin.
=> fix(ingress): don't fetch skins for players without uuids

crates/hyperion-proto/src/server_to_proxy.rs, crates/hyperion-proxy/src/cache.rs, crates/hyperion-proxy/src/data.rs, crates/hyperion-proxy/src/egress.rs, crates/hyperion-proxy/src/player.rs, crates/hyperion/src/egress/player_join/mod.rs, crates/hyperion/src/ingress/mod.rs, crates/hyperion/src/net/mod.rs
When a client sends a malformed packet, the server will crash because it used entity.destruct to disconnect players for malformed packets which leads to an abort because, when the server receives PlayerDisconnect from the proxy, the server will try to set PendingRemove on the already-destructed entity.
This PR fixes these errors on player disconnects.
=> fix: malformed packet crash

crates/hyperion-inventory/src/lib.rs
- prevent panic when mutating invalid inventory slots
- `cargo fmt --all -- --check` *(fails: could not download toolchain)*
- `cargo test --locked --all --no-run` *(fails: could not download toolchain)*
=> fix: inventory slot bounds check

.github/workflows/publish.yml
The arm-hooray runner seems to be missing causing the arm64 workflow to time out. Hyperion does not have architecture-specific code, so the arm64 build is not necessary because the program will likely compile on arm64 if compilation succeeds on other architectures.
=> fix(ci): disable arm64 build

crates/hyperion/src/net/proxy.rs
peer_addr can fail. Connections from tools like nmap seem to trigger ENOTCONN.
=> fix: handle peer_addr error

crates/geometry/src/ray.rs
This isn't needed because the reciprocal of 0 will return inf instead of NaN, so checking for NaN in the reciprocal is not needed. The NaN check is only needed later in Ray::voxel_traversal because 0 * inf = NaN
=> perf: remove NaN check in Ray::new

crates/hyperion-proxy/src/player.rs
This ensures that all packets, especially the disconnect message packet, are sent to the client before the server disconnects the client.
=> fix: flush packets before shutdown

crates/hyperion/src/egress/channel.rs, crates/hyperion/src/egress/mod.rs, crates/hyperion/src/lib.rs, crates/hyperion/src/net/intermediate.rs, crates/hyperion/src/net/mod.rs, crates/hyperion/src/net/proxy.rs, crates/hyperion/src/simulation/mod.rs
=> feat: support multiple connected proxies
