hyperion-mc/hyperion

server/src/main.rs
=> feat: player joins server

.cargo/config.toml, Dockerfile, server/src/packets.rs
=> feat: improve docker build time

.cargo/config.toml, Cargo.lock, Dockerfile, README.md, docker-compose.yml, server/src/main.rs, server/src/packets.rs, server/src/quad_tree.rs, server/src/system/entity_detect_collisions.rs
Thank you @rj00a https://github.com/rj00a/evenio/pull/30
=> feat: calculate collisions in parallel

crates/server/src/system/player_join_world.rs
- this massively improves client frames
=> feat: remove name tags from players

crates/server/src/net.rs, crates/server/src/net/encoder.rs, crates/server/src/net/linux.rs, crates/server/src/singleton/broadcast.rs, crates/server/src/singleton/buffer_allocator.rs, crates/server/src/system/egress.rs, crates/server/src/system/player_join_world.rs
improves #292 but does not fix it entirely.
=> fix: login

crates/server/src/packets.rs, crates/server/src/system/ingress.rs
- enables features that were previously removed after io uring changes
=> feat: add back packet `switch`

README.md, crates/server/src/blocks.rs, crates/server/src/system/player_join_world.rs
=> fix: map loading for linux

Cargo.lock, Cargo.toml, crates/rayon-local/src/lib.rs, crates/server/Cargo.toml, crates/server/src/components/chunks.rs, crates/server/src/lib.rs, crates/server/src/net.rs, crates/server/src/net/buffers.rs, crates/server/src/net/encoder.rs, crates/server/src/net/generic.rs, crates/server/src/net/linux.rs, crates/server/src/packets.rs, crates/server/src/singleton/ring.rs, crates/server/src/system.rs, crates/server/src/system/disguise_player.rs, crates/server/src/system/egress.rs, crates/server/src/system/ingress.rs, crates/server/src/system/init_player.rs, crates/server/src/system/player_join_world.rs, crates/server/src/system/send_chunk_updates.rs, crates/server/src/system/set_player_skin.rs, crates/server/src/system/sync_entity_position.rs, crates/server/src/system/time.rs
=> feat: improved iou times

crates/server/src/net.rs, crates/server/src/net/generic.rs, crates/server/src/net/linux.rs, crates/server/src/system/ingress.rs
=> feat: remove unsafe `'static`

crates/server/src/net.rs, crates/server/src/net/generic.rs, crates/server/src/net/linux.rs, crates/server/src/system/egress.rs, crates/server/src/system/ingress.rs
- will no longer crash server with `mio` impl
=> fix: improve disconnect handling

crates/server/src/system/update_equipment.rs
=> fix: sync main hand changes

crates/server/src/components/chunks.rs, crates/server/src/system/block_update.rs, crates/server/src/system/ingress.rs, events/infection/src/lib.rs, events/infection/src/system.rs
Players can now access block states in chunks, which is very useful for implementing physics.
Related:
#434 
#254
=> feat: provide API access for block states

crates/server/src/event.rs, crates/server/src/inventory.rs, crates/server/src/lib.rs, crates/server/src/packets.rs, crates/server/src/system.rs, crates/server/src/system/ingress.rs, crates/server/src/system/inventory_systems.rs, crates/server/src/system/release_item.rs
Addresses #447 
https://github.com/andrewgazelka/hyperion/assets/15882635/197d8d9e-8ca7-42fb-9925-9fc88fc1d421
=> feat: bow draw

events/tag/src/command/class.rs
Fixes one of the issues of https://github.com/andrewgazelka/hyperion/issues/613
=> Fix inventory clear bug when selecting class

.github/workflows/build.yml, Dockerfile, crates/bvh-region/Cargo.toml, crates/hyperion-clap-macros/Cargo.toml, crates/hyperion-clap/Cargo.toml, crates/hyperion-command/Cargo.toml, crates/hyperion-crafting/Cargo.toml, crates/hyperion-event-macros/Cargo.toml, crates/hyperion-inventory/Cargo.toml, crates/hyperion-minecraft-proto/Cargo.toml, crates/hyperion-nerd-font/Cargo.toml, crates/hyperion-palette/Cargo.toml, crates/hyperion-permission/Cargo.toml, crates/hyperion-proto/Cargo.toml, crates/hyperion-proxy/Cargo.toml, crates/hyperion-scheduled/Cargo.toml, crates/hyperion-stats/Cargo.toml, crates/hyperion-text/Cargo.toml, crates/hyperion-utils/Cargo.toml, crates/hyperion/Cargo.toml, events/tag/Cargo.toml, rust-toolchain.toml
chore: update rust toolchain
update latest rust
=> chore: update rust toolchain

events/tag/src/command/class.rs
=> Re-sync xp bar on changing skin

.cargo/config.toml, crates/geometry/src/ray.rs, crates/hyperion/src/lib.rs, crates/hyperion/src/simulation/blocks/mod.rs, events/tag/src/command/raycast.rs
`Ray::voxel_traversal` and `get_direction_from_rotation` were implemented wrong.
=> fix: raycast traversal

Cargo.lock, Cargo.toml, crates/hyperion-clap/src/lib.rs, crates/hyperion-proto/Cargo.toml, crates/hyperion-proto/src/shared.rs, crates/hyperion/src/common/config.rs, crates/hyperion/src/egress/mod.rs, crates/hyperion/src/egress/player_join/mod.rs, crates/hyperion/src/egress/sync_chunks.rs, crates/hyperion/src/egress/sync_entity_state.rs, crates/hyperion/src/net/mod.rs, crates/hyperion/src/simulation/blocks/frame.rs, crates/hyperion/src/simulation/blocks/loader/mod.rs, crates/hyperion/src/simulation/blocks/manager.rs, crates/hyperion/src/simulation/blocks/mod.rs, crates/hyperion/src/simulation/mod.rs, events/tag/Cargo.toml, events/tag/src/command/class.rs, events/tag/src/command/fly.rs, events/tag/src/command/replace.rs, events/tag/src/command/speed.rs, events/tag/src/module/spawn.rs, events/tag/src/skin.rs
still need to fix initial yaw/pitch
=> fix(hyperion): general arrow heading

Cargo.lock, Cargo.toml, tools/packet-inspector/Cargo.toml, tools/packet-inspector/README.md, tools/packet-inspector/build.rs, tools/packet-inspector/extracted/packets.json, tools/packet-inspector/src/app.rs, tools/packet-inspector/src/app/connection.rs, tools/packet-inspector/src/app/filter.rs, tools/packet-inspector/src/app/hex_viewer.rs, tools/packet-inspector/src/app/packet_list.rs, tools/packet-inspector/src/app/text_viewer.rs, tools/packet-inspector/src/lib.rs, tools/packet-inspector/src/main.rs, tools/packet-inspector/src/main_cli.rs, tools/packet-inspector/src/packet_io.rs, tools/packet-inspector/src/packet_registry.rs, tools/packet-inspector/src/shared_state.rs, tools/packet-inspector/src/tri_checkbox.rs
from [Valence](https://github.com/valence-rs/valence/tree/main/tools/packet_inspector)
=> feat(tool): add packet inspector tool

Cargo.lock, crates/hyperion/src/common/mod.rs, crates/hyperion/src/lib.rs, events/tag/Cargo.toml, events/tag/src/lib.rs, events/tag/src/main.rs
- allows for easier testing of ECS
=> feat: `Hyperion` is now a module

crates/hyperion-respawn/src/lib.rs, crates/hyperion/src/simulation/handlers.rs, crates/hyperion/src/storage/event/sync.rs, events/tag/src/lib.rs, events/tag/src/module/attack.rs, events/tag/src/module/spawn.rs
=> feat: respawn near ally and distribute xp

crates/hyperion/src/ingress/mod.rs, crates/hyperion/src/simulation/event.rs, crates/hyperion/src/simulation/handlers.rs, crates/hyperion/src/storage/event/queue/mod.rs, events/tag/src/command/replace.rs
Fixes #794 
Add StartDestroyBlock event
Changes to replace command
=> fix: some block related fixes & changes

tools/rust-mc-bot/src/lib.rs, tools/rust-mc-bot/src/main.rs
im gonna test this when i get home
=> fix: rust-mc-bot for windows

events/tag/src/module/attack.rs
=> feat: add critical hits

.dockerignore, Cargo.lock, Dockerfile, crates/hyperion-proxy/Cargo.toml, crates/hyperion-proxy/src/main.rs, docker-compose.yml, events/tag/Cargo.toml, events/tag/src/main.rs, tools/rust-mc-bot/Cargo.toml, tools/rust-mc-bot/src/main.rs
- improves docker/container experience
=> feat: use environment variables to configure

README.md
This Discord server no longer exists.
=> docs: remove broken Discord invite

crates/hyperion/src/net/proxy.rs
next_server_packet_buffer originally went into an infinite loop when the proxy connection closed. The code has been changed to use read_exact which will return UnexpectedEof when the proxy connection is closed.
=> fix: handle proxy eof
